AllCops:
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 7
